ChibiOS/NIL: ChNilTimer1
ChNilTimer1
Detailed Description
Nil RTOS timer 1 functions.
Functions
void chTimer1Start (uint32_t microseconds)
void chTimer1Stop ()
bool chTimer1Wait ()
Function Documentation
void chTimer1Start (uint32_t microseconds)
Start periodic timer 1 signals.
Parameters
[in] microseconds The period in microseconds between signals.
Note
The maximum value for microseconds is 4,194,304 for a 16 MHz CPU.
Definition at line 36 of file ChNilTimer1.cpp.
References chSysLock, chSysUnlock, and chTimer1Stop().
void chTimer1Stop ()
Stop timer1 signals.
Definition at line 81 of file ChNilTimer1.cpp.
Referenced by chTimer1Start().
bool chTimer1Wait ()
Sleep while waiting for timer1 signal.
Note
This function should not be used in the idle thread.
Returns
true if success or false if overrun or error.
Definition at line 90 of file ChNilTimer1.cpp.
References chIsIdleThread, chSemWait, chSemWaitTimeout(), MSG_TIMEOUT, and TIME_IMMEDIATE.