ChibiOS/NIL: Arduino port
Arduino port
Detailed Description
ChNil Added functions for Arduino port.
Macros
#define chIsIdleThread() (nil.current == &nil.threads[chCfgNumThreads])
Returns true if current thread is the idle thread.
Functions
static char * heapEnd ()
static size_t heapSize ()
void chBegin ()
void chFillStacks ()
void chPrintStackSizes (Print *pr)
void chPrintUnusedStack (Print *pr)
Variables
char * __brkval
char __bss_end
Macro Definition Documentation
#define chIsIdleThread () (nil.current == &nil.threads[chCfgNumThreads])
Returns true if current thread is the idle thread.
Definition at line 20 of file ChNil.h.
Referenced by chAnalogRead(), and chTimer1Wait().
Function Documentation
static char* heapEnd () inline static
Returns
Address of first byte after the heap.
Definition at line 19 of file ChNil.cpp.
References __brkval, and __bss_end.
Referenced by chFillStacks(), and chPrintUnusedStack().
static size_t heapSize () inline static
Returns
Size of heap and idle thread stack in bytes.
Definition at line 25 of file ChNil.cpp.
Referenced by chPrintStackSizes().
void chBegin ()
start the chNil.
Definition at line 41 of file ChNil.cpp.
References chSysInit(), chSysLock, and halInit().
void chFillStacks ()
Fill stacks with 0X55.
Definition at line 47 of file ChNil.cpp.
References chSysLock, chSysUnlock, and heapEnd().
void chPrintStackSizes (Print * pr)
Print size of all all stacks.
Parameters
[in] pr Print stream for output.
Definition at line 60 of file ChNil.cpp.
References heapSize(), nil_thread_cfg::wbase, and nil_thread_cfg::wend.
void chPrintUnusedStack (Print * pr)
Print unused byte count for all stacks.
Parameters
[in] pr Print stream for output.
Stacks must be filled by chFillStacks().
Definition at line 71 of file ChNil.cpp.
References heapEnd().
Variable Documentation
char* __brkval
boundary between stack and heap.
Referenced by heapEnd().
char __bss_end
End of bss section.
Referenced by heapEnd().