ChibiOS/NIL: API
API
NIL Kernel
Detailed Description
Macros
#define _CHIBIOS_NIL_
ChibiOS/NIL identification macro.
#define CH_KERNEL_STABLE 0
Stable release flag.
#define CH_CFG_ST_RESOLUTION 32
Number of user threads in the application.
#define CH_CFG_ST_FREQUENCY 100
System tick frequency.
#define CH_CFG_ST_TIMEDELTA 0
Time delta constant for the tick-less mode.
#define CH_CFG_USE_SEMAPHORES TRUE
Semaphores APIs.
#define CH_CFG_USE_MUTEXES FALSE
Mutexes APIs.
#define CH_CFG_USE_EVENTS TRUE
Events Flags APIs.
#define CH_CFG_USE_MAILBOXES TRUE
Mailboxes APIs.
#define CH_CFG_USE_MEMCORE TRUE
Core Memory Manager APIs.
#define CH_CFG_USE_HEAP TRUE
Heap Allocator APIs.
#define CH_CFG_USE_MEMPOOLS TRUE
Memory Pools Allocator APIs.
#define CH_DBG_STATISTICS FALSE
Debug option, kernel statistics.
#define CH_DBG_SYSTEM_STATE_CHECK FALSE
Debug option, system state check.
#define CH_DBG_ENABLE_CHECKS FALSE
Debug option, parameters checks.
#define CH_DBG_ENABLE_ASSERTS FALSE
System assertions.
#define CH_DBG_ENABLE_STACK_CHECK FALSE
Stack check.
#define CH_CFG_SYSTEM_INIT_HOOK() {}
System initialization hook.
#define CH_CFG_THREAD_EXT_FIELDS
Threads descriptor structure extension.
#define CH_CFG_THREAD_EXT_INIT_HOOK(tr) {}
Threads initialization hook.
#define CH_CFG_IDLE_ENTER_HOOK() {}
Idle thread enter hook.
#define CH_CFG_IDLE_LEAVE_HOOK() {}
Idle thread leave hook.
#define CH_CFG_SYSTEM_HALT_HOOK(reason) {}
System halt hook.
#define THD_IDLE_BASE (&__main_thread_stack_base__)
#define __CH_STRINGIFY(a) #a
Utility to make the parameter a quoted string.
ChibiOS/NIL version identification
#define CH_KERNEL_VERSION "2.0.0"
Kernel version string.
#define CH_KERNEL_MAJOR 2
Kernel version major number.
#define CH_KERNEL_MINOR 0
Kernel version minor number.
#define CH_KERNEL_PATCH 0
Kernel version patch number.
Wakeup messages
#define MSG_OK (msg_t)0
OK wakeup message.
#define MSG_TIMEOUT (msg_t)-1
Wake-up caused by a timeout condition.
#define MSG_RESET (msg_t)-2
Wake-up caused by a reset condition.
Special time constants
#define TIME_IMMEDIATE ((systime_t)-1)
Zero time specification for some functions with a timeout specification.
#define TIME_INFINITE ((systime_t)0)
Infinite time specification for all functions with a timeout specification.
Thread state related macros
#define NIL_STATE_READY (tstate_t)0
Thread ready or executing.
#define NIL_STATE_SLEEPING (tstate_t)1
Thread sleeping.
#define NIL_STATE_SUSP (tstate_t)2
Thread suspended.
#define NIL_STATE_WTSEM (tstate_t)3
On semaphore.
#define NIL_STATE_WTOREVT (tstate_t)4
Waiting for events.
#define NIL_THD_IS_READY(tr) ((tr)->state == NIL_STATE_READY)
#define NIL_THD_IS_SLEEPING(tr) ((tr)->state == NIL_STATE_SLEEPING)
#define NIL_THD_IS_SUSP(tr) ((tr)->state == NIL_STATE_SUSP)
#define NIL_THD_IS_WTSEM(tr) ((tr)->state == NIL_STATE_WTSEM)
#define NIL_THD_IS_WTOREVT(tr) ((tr)->state == NIL_STATE_WTOREVT)
Events related macros
#define ALL_EVENTS ((eventmask_t)-1)
All events allowed mask.
#define EVENT_MASK(eid) ((eventmask_t)(1 << (eid)))
Returns an event mask from an event identifier.
Threads tables definition macros
size_t chCfgNumThreads
thread_t nil_threads []
#define THD_TABLE_BEGIN const thread_config_t nil_thd_configs[] = {
Start of user threads table.
#define THD_TABLE_ENTRY(wap, name, funcp, arg)
Entry of user threads table.
#define THD_TABLE_END
End of user threads table.
Memory alignment support macros
#define MEM_ALIGN_MASK(a) ((size_t)(a) - 1U)
Alignment mask constant.
#define MEM_ALIGN_PREV(p, a) ((size_t)(p) & ~MEM_ALIGN_MASK(a))
Aligns to the previous aligned memory address.
#define MEM_ALIGN_NEXT(p, a)
Aligns to the new aligned memory address.
#define MEM_IS_ALIGNED(p, a) (((size_t)(p) & MEM_ALIGN_MASK(a)) == 0U)
Returns whatever a pointer or memory size is aligned.
#define MEM_IS_VALID_ALIGNMENT(a) (((size_t)(a) != 0U) && (((size_t)(a) & ((size_t)(a) - 1U)) == 0U))
Returns whatever a constant is a valid alignment.
Working Areas
#define THD_WORKING_AREA_SIZE(n)
Calculates the total Working Area size.
#define THD_WORKING_AREA(s, n) PORT_WORKING_AREA(s, n)
Static working area allocation.
Threads abstraction macros
#define THD_FUNCTION(tname, arg) PORT_THD_FUNCTION(tname, arg)
Thread declaration macro.
ISRs abstraction macros
#define CH_IRQ_IS_VALID_PRIORITY(prio) PORT_IRQ_IS_VALID_PRIORITY(prio)
Priority level validation macro.
#define CH_IRQ_IS_VALID_KERNEL_PRIORITY(prio) PORT_IRQ_IS_VALID_KERNEL_PRIORITY(prio)
Priority level validation macro.
#define CH_IRQ_PROLOGUE()
IRQ handler enter code.
#define CH_IRQ_EPILOGUE()
IRQ handler exit code.
#define CH_IRQ_HANDLER(id) PORT_IRQ_HANDLER(id)
Standard normal IRQ handler declaration.
Fast ISRs abstraction macros
#define CH_FAST_IRQ_HANDLER(id) PORT_FAST_IRQ_HANDLER(id)
Standard fast IRQ handler declaration.
Time conversion utilities
#define S2ST(sec) ((systime_t)((uint32_t)(sec) * (uint32_t)CH_CFG_ST_FREQUENCY))
Seconds to system ticks.
#define MS2ST(msec)
Milliseconds to system ticks.
#define US2ST(usec)
Microseconds to system ticks.
Time conversion utilities for the realtime counter
#define S2RTC(freq, sec) ((freq) * (sec))
Seconds to realtime counter.
#define MS2RTC(freq, msec) (rtcnt_t)((((freq) + 999UL) / 1000UL) * (msec))
Milliseconds to realtime counter.
#define US2RTC(freq, usec) (rtcnt_t)((((freq) + 999999UL) / 1000000UL) * (usec))
Microseconds to realtime counter.
Semaphores macros
#define _SEMAPHORE_DATA(name, n) {n}
Data part of a static semaphore initializer.
#define SEMAPHORE_DECL(name, n) semaphore_t name = _SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Macro Functions
#define chSysGetRealtimeCounterX() (rtcnt_t)port_rt_get_counter_value()
Returns the current value of the system real time counter.
#define chSysDisable()
Raises the system interrupt priority mask to the maximum level.
#define chSysSuspend()
Raises the system interrupt priority mask to system level.
#define chSysEnable()
Lowers the system interrupt priority mask to user level.
#define chSysLock()
Enters the kernel lock state.
#define chSysUnlock()
Leaves the kernel lock state.
#define chSysLockFromISR()
Enters the kernel lock state from within an interrupt handler.
#define chSysUnlockFromISR()
Leaves the kernel lock state from within an interrupt handler.
#define chSchIsRescRequiredI() ((bool)(nil.current != nil.next))
Evaluates if a reschedule is required.
#define chThdGetSelfX() nil.current
Returns a pointer to the current thread_t.
#define chThdSleepSeconds(sec) chThdSleep(S2ST(sec))
Delays the invoking thread for the specified number of seconds.
#define chThdSleepMilliseconds(msec) chThdSleep(MS2ST(msec))
Delays the invoking thread for the specified number of milliseconds.
#define chThdSleepMicroseconds(usec) chThdSleep(US2ST(usec))
Delays the invoking thread for the specified number of microseconds.
#define chThdSleepS(timeout) (void) chSchGoSleepTimeoutS(NIL_STATE_SLEEPING, timeout)
Suspends the invoking thread for the specified time.
#define chThdSleepUntilS(abstime)
Suspends the invoking thread until the system time arrives to the specified value.
#define chSemObjectInit(sp, n) ((sp)->cnt = n)
Initializes a semaphore with the specified counter value.
#define chSemWait(sp) chSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define chSemWaitS(sp) chSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define chSemFastWaitI(sp) ((sp)->cnt--)
Decreases the semaphore counter.
#define chSemFastSignalI(sp) ((sp)->cnt++)
Increases the semaphore counter.
#define chSemGetCounterI(sp) ((sp)->cnt)
Returns the semaphore counter current value.
#define chVTGetSystemTimeX() (nil.systime)
Current system time.
#define chVTTimeElapsedSinceX(start) ((systime_t)(chVTGetSystemTimeX() - (start)))
Returns the elapsed time since the specified start time.
#define chVTIsTimeWithinX(time, start, end) ((bool)((systime_t)((time) - (start)) < (systime_t)((end) - (start))))
Checks if the specified time is within the specified time window.
#define chDbgCheck(c)
Function parameters check.
#define chDbgAssert(c, r)
Condition assertion.
Typedefs
typedef uint32_t systime_t
Type of system time.
typedef struct nil_thread thread_t
Type of a structure representing a thread.
typedef struct nil_semaphore semaphore_t
Type of a structure representing a semaphore.
typedef void(* tfunc_t) (void *p)
Thread function.
typedef struct nil_thread_cfg thread_config_t
Type of a structure representing a thread static configuration.
typedef thread_t * thread_reference_t
Type of a thread reference.
typedef struct nil_system nil_system_t
Type of a structure representing the system.
Data Structures
struct nil_semaphore
Structure representing a counting semaphore.
struct nil_thread_cfg
Structure representing a thread static configuration.
struct nil_thread
Structure representing a thread.
struct nil_system
System data structure.
Functions
void _dbg_check_disable (void)
Guard code for chSysDisable().
void _dbg_check_suspend (void)
Guard code for chSysSuspend().
void _dbg_check_enable (void)
Guard code for chSysEnable().
void _dbg_check_lock (void)
Guard code for chSysLock().
void _dbg_check_unlock (void)
Guard code for chSysUnlock().
void _dbg_check_lock_from_isr (void)
Guard code for chSysLockFromIsr().
void _dbg_check_unlock_from_isr (void)
Guard code for chSysUnlockFromIsr().
void _dbg_check_enter_isr (void)
Guard code for CH_IRQ_PROLOGUE().
void _dbg_check_leave_isr (void)
Guard code for CH_IRQ_EPILOGUE().
void chDbgCheckClassI (void)
I-class functions context check.
void chDbgCheckClassS (void)
S-class functions context check.
void chSysInit (void)
Initializes the kernel.
void chSysHalt (const char *reason)
Halts the system.
void chSysTimerHandlerI (void)
Time management handler.
void chSysUnconditionalLock (void)
Unconditionally enters the kernel lock state.
void chSysUnconditionalUnlock (void)
Unconditionally leaves the kernel lock state.
syssts_t chSysGetStatusAndLockX (void)
Returns the execution status and enters a critical zone.
void chSysRestoreStatusX (syssts_t sts)
Restores the specified execution status and leaves a critical zone.
bool chSysIsCounterWithinX (rtcnt_t cnt, rtcnt_t start, rtcnt_t end)
Realtime window test.
void chSysPolledDelayX (rtcnt_t cycles)
Polled delay.
thread_t * chSchReadyI (thread_t *tp, msg_t msg)
Makes the specified thread ready for execution.
bool chSchIsPreemptionRequired (void)
Evaluates if preemption is required.
void chSchDoReschedule (void)
Switches to the first thread on the runnable queue.
void chSchRescheduleS (void)
Reschedules if needed.
msg_t chSchGoSleepTimeoutS (tstate_t newstate, systime_t timeout)
Puts the current thread to sleep into the specified state with timeout specification.
msg_t chThdSuspendTimeoutS (thread_reference_t *trp, systime_t timeout)
Sends the current thread sleeping and sets a reference variable.
void chThdResumeI (thread_reference_t *trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
void chThdSleep (systime_t timeout)
Suspends the invoking thread for the specified time.
void chThdSleepUntil (systime_t abstime)
Suspends the invoking thread until the system time arrives to the specified value.
msg_t chSemWaitTimeout (semaphore_t *sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
msg_t chSemWaitTimeoutS (semaphore_t *sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
void chSemSignal (semaphore_t *sp)
Performs a signal operation on a semaphore.
void chSemSignalI (semaphore_t *sp)
Performs a signal operation on a semaphore.
void chSemReset (semaphore_t *sp, cnt_t n)
Performs a reset operation on the semaphore.
void chSemResetI (semaphore_t *sp, cnt_t n)
Performs a reset operation on the semaphore.
void chEvtSignal (thread_t *tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
void chEvtSignalI (thread_t *tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
eventmask_t chEvtWaitAnyTimeout (eventmask_t mask, systime_t timeout)
Waits for any of the specified events.
Variables
nil_system_t nil
System data structures.
Macro Definition Documentation
#define _CHIBIOS_NIL_
ChibiOS/NIL identification macro.
Definition at line 46 of file ch.h.
#define CH_KERNEL_STABLE 0
Stable release flag.
Definition at line 51 of file ch.h.
#define CH_KERNEL_VERSION "2.0.0"
Kernel version string.
Definition at line 60 of file ch.h.
#define CH_KERNEL_MAJOR 2
Kernel version major number.
Definition at line 65 of file ch.h.
#define CH_KERNEL_MINOR 0
Kernel version minor number.
Definition at line 70 of file ch.h.
#define CH_KERNEL_PATCH 0
Kernel version patch number.
Definition at line 75 of file ch.h.
#define MSG_OK (msg_t)0
OK wakeup message.
Definition at line 82 of file ch.h.
Referenced by chEvtSignalI(), chEvtWaitAnyTimeout(), chGuardedPoolAllocTimeoutS(), chMBFetchI(), chMBFetchS(), chMBPostAheadI(), chMBPostAheadS(), chMBPostI(), chMBPostS(), chSemSignalI(), and chSemWaitTimeoutS().
#define MSG_TIMEOUT (msg_t)-1
Wake-up caused by a timeout condition.
Definition at line 83 of file ch.h.
Referenced by chMBFetchI(), chMBPostAheadI(), chMBPostI(), chSemWaitTimeoutS(), chSysTimerHandlerI(), and chTimer1Wait().
#define MSG_RESET (msg_t)-2
Wake-up caused by a reset condition.
Definition at line 86 of file ch.h.
Referenced by chSemResetI().
#define TIME_IMMEDIATE ((systime_t)-1)
Zero time specification for some functions with a timeout specification.
Note
Not all functions accept TIME_IMMEDIATE as timeout parameter, see the specific function documentation.
Definition at line 101 of file ch.h.
Referenced by chEvtWaitAnyTimeout(), chSemWaitTimeoutS(), and chTimer1Wait().
#define TIME_INFINITE ((systime_t)0)
Infinite time specification for all functions with a timeout specification.
Definition at line 107 of file ch.h.
Referenced by chSchGoSleepTimeoutS(), and osalThreadSuspendS().
#define NIL_STATE_READY (tstate_t)0
Thread ready or executing.
Definition at line 114 of file ch.h.
Referenced by chSchReadyI().
#define NIL_STATE_SLEEPING (tstate_t)1
Thread sleeping.
Definition at line 117 of file ch.h.
#define NIL_STATE_SUSP (tstate_t)2
Thread suspended.
Definition at line 118 of file ch.h.
Referenced by chThdSuspendTimeoutS().
#define NIL_STATE_WTSEM (tstate_t)3
On semaphore.
Definition at line 119 of file ch.h.
Referenced by chSemWaitTimeoutS().
#define NIL_STATE_WTOREVT (tstate_t)4
Waiting for events.
Definition at line 120 of file ch.h.
Referenced by chEvtWaitAnyTimeout().
#define ALL_EVENTS ((eventmask_t)-1)
All events allowed mask.
Definition at line 135 of file ch.h.
#define EVENT_MASK (eid) ((eventmask_t)(1 << (eid)))
Returns an event mask from an event identifier.
Definition at line 140 of file ch.h.
#define CH_CFG_ST_RESOLUTION 32
Number of user threads in the application.
Note
This number is not inclusive of the idle thread which is implicitly handled. System time counter resolution.
Allowed values are 16 or 32 bits.
Definition at line 163 of file ch.h.
#define CH_CFG_ST_FREQUENCY 100
System tick frequency.
Note
This value together with the CH_CFG_ST_RESOLUTION option defines the maximum amount of time allowed for timeouts.
Definition at line 173 of file ch.h.
#define CH_CFG_ST_TIMEDELTA 0
Time delta constant for the tick-less mode.
Note
If this value is zero then the system uses the classic periodic tick. This value represents the minimum number of ticks that is safe to specify in a timeout directive. The value one is not valid, timeouts are rounded up to this value.
Definition at line 185 of file ch.h.
Referenced by chSchGoSleepTimeoutS().
#define CH_CFG_USE_SEMAPHORES TRUE
Semaphores APIs.
If enabled then the Semaphores APIs are included in the kernel.
Note
The default is TRUE.
Definition at line 195 of file ch.h.
#define CH_CFG_USE_MUTEXES FALSE
Mutexes APIs.
If enabled then the mutexes APIs are included in the kernel.
Note
Feature not currently implemented.
The default is FALSE.
Definition at line 206 of file ch.h.
#define CH_CFG_USE_EVENTS TRUE
Events Flags APIs.
If enabled then the event flags APIs are included in the kernel.
Note
The default is TRUE.
Definition at line 216 of file ch.h.
#define CH_CFG_USE_MAILBOXES TRUE
Mailboxes APIs.
If enabled then the asynchronous messages (mailboxes) APIs are included in the kernel.
Note
The default is TRUE.
Requires CH_CFG_USE_SEMAPHORES.
Definition at line 228 of file ch.h.
#define CH_CFG_USE_MEMCORE TRUE
Core Memory Manager APIs.
If enabled then the core memory manager APIs are included in the kernel.
Note
The default is TRUE.
Definition at line 239 of file ch.h.
#define CH_CFG_USE_HEAP TRUE
Heap Allocator APIs.
If enabled then the memory heap allocator APIs are included in the kernel.
Note
The default is TRUE.
Definition at line 250 of file ch.h.
#define CH_CFG_USE_MEMPOOLS TRUE
Memory Pools Allocator APIs.
If enabled then the memory pools allocator APIs are included in the kernel.
Note
The default is TRUE.
Definition at line 261 of file ch.h.
#define CH_DBG_STATISTICS FALSE
Debug option, kernel statistics.
Note
Feature not currently implemented.
The default is FALSE.
Definition at line 271 of file ch.h.
#define CH_DBG_SYSTEM_STATE_CHECK FALSE
Debug option, system state check.
Note
This is a planned feature, not yet implemented.
The default is FALSE.
Definition at line 281 of file ch.h.
#define CH_DBG_ENABLE_CHECKS FALSE
Debug option, parameters checks.
Note
The default is FALSE.
Definition at line 290 of file ch.h.
#define CH_DBG_ENABLE_ASSERTS FALSE
System assertions.
Note
The default is FALSE.
Definition at line 299 of file ch.h.
#define CH_DBG_ENABLE_STACK_CHECK FALSE
Stack check.
Note
The default is FALSE.
Definition at line 308 of file ch.h.
#define CH_CFG_SYSTEM_INIT_HOOK () {}
System initialization hook.
Definition at line 315 of file ch.h.
Referenced by chSysInit().
#define CH_CFG_THREAD_EXT_FIELDS
Threads descriptor structure extension.
User fields added to the end of the thread_t structure.
Definition at line 323 of file ch.h.
#define CH_CFG_THREAD_EXT_INIT_HOOK (tr) {}
Threads initialization hook.
Definition at line 330 of file ch.h.
Referenced by chSysInit().
#define CH_CFG_IDLE_ENTER_HOOK () {}
Idle thread enter hook.
Note
This hook is invoked within a critical zone, no OS functions should be invoked from here.
This macro can be used to activate a power saving mode.
Definition at line 340 of file ch.h.
Referenced by chSchGoSleepTimeoutS().
#define CH_CFG_IDLE_LEAVE_HOOK () {}
Idle thread leave hook.
Note
This hook is invoked within a critical zone, no OS functions should be invoked from here.
This macro can be used to deactivate a power saving mode.
Definition at line 350 of file ch.h.
Referenced by chSchDoReschedule().
#define CH_CFG_SYSTEM_HALT_HOOK (reason) {}
System halt hook.
Definition at line 357 of file ch.h.
Referenced by chSysHalt().
#define THD_IDLE_BASE (&__main_thread_stack_base__)
Boundaries of the idle thread boundaries, only required if stack checking is enabled.
Definition at line 457 of file ch.h.
Referenced by chSysInit().
#define __CH_STRINGIFY (a) #a
Utility to make the parameter a quoted string.
Definition at line 635 of file ch.h.
#define THD_TABLE_BEGIN const thread_config_t nil_thd_configs[] = {
Start of user threads table.
Definition at line 646 of file ch.h.
#define THD_TABLE_ENTRY (wap, name, funcp, arg)
Value:
{wap, ((stkalign_t *)(wap)) + (sizeof (wap) / sizeof(stkalign_t)),        \
   name, funcp, arg},
Entry of user threads table.
Definition at line 652 of file ch.h.
#define THD_TABLE_END
Value:
{THD_IDLE_BASE, THD_IDLE_END, "idle", NULL, NULL}};     \
size_t chCfgNumThreads = sizeof(nil_thd_configs)/sizeof(thread_config_t) - 1; \
thread_t nil_threads[sizeof(nil_thd_configs)/sizeof(thread_config_t)];
End of user threads table.
Definition at line 659 of file ch.h.
#define MEM_ALIGN_MASK (a) ((size_t)(a) - 1U)
Alignment mask constant.
Parameters
[in] a alignment, must be a power of two
Definition at line 700 of file ch.h.
#define MEM_ALIGN_PREV (p, a) ((size_t)(p) & ~MEM_ALIGN_MASK(a))
Aligns to the previous aligned memory address.
Parameters
[in] p variable to be aligned
[in] a alignment, must be a power of two
Definition at line 708 of file ch.h.
#define MEM_ALIGN_NEXT (p, a)
Value:
MEM_ALIGN_PREV((size_t)(p) +                \
                                               MEM_ALIGN_MASK(a), (a))
Aligns to the new aligned memory address.
Parameters
[in] p variable to be aligned
[in] a alignment, must be a power of two
Definition at line 716 of file ch.h.
Referenced by chCoreAllocAlignedI(), chHeapAllocAligned(), and chHeapFree().
#define MEM_IS_ALIGNED (p, a) (((size_t)(p) & MEM_ALIGN_MASK(a)) == 0U)
Returns whatever a pointer or memory size is aligned.
Parameters
[in] p variable to be aligned
[in] a alignment, must be a power of two
Definition at line 725 of file ch.h.
Referenced by chHeapFree(), and chHeapObjectInit().
#define MEM_IS_VALID_ALIGNMENT (a) (((size_t)(a) != 0U) && (((size_t)(a) & ((size_t)(a) - 1U)) == 0U))
Returns whatever a constant is a valid alignment.
Valid alignments are powers of two.
Parameters
[in] a alignment to be checked, must be a constant
Definition at line 733 of file ch.h.
Referenced by chCoreAllocAlignedI(), and chHeapAllocAligned().
#define THD_WORKING_AREA_SIZE (n)
Value:
MEM_ALIGN_NEXT(PORT_WA_SIZE(n),            \
                                                PORT_STACK_ALIGN)
Calculates the total Working Area size.
Parameters
[in] n the stack size to be assigned to the thread
Returns
The total used memory in bytes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 748 of file ch.h.
#define THD_WORKING_AREA (s, n) PORT_WORKING_AREA(s, n)
Static working area allocation.
This macro is used to allocate a static thread working area aligned as both position and size.
Parameters
[in] s the name to be assigned to the stack array
[in] n the stack size to be assigned to the thread
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 761 of file ch.h.
#define THD_FUNCTION (tname, arg) PORT_THD_FUNCTION(tname, arg)
Thread declaration macro.
Note
Thread declarations should be performed using this macro because the port layer could define optimizations for thread functions.
Definition at line 772 of file ch.h.
#define CH_IRQ_IS_VALID_PRIORITY (prio) PORT_IRQ_IS_VALID_PRIORITY(prio)
Priority level validation macro.
This macro determines if the passed value is a valid priority level for the underlying architecture.
Parameters
[in] prio the priority level
Returns
Priority range result.
Return values
false if the priority is invalid or if the architecture does not support priorities.
true if the priority is valid.
Definition at line 790 of file ch.h.
#define CH_IRQ_IS_VALID_KERNEL_PRIORITY (prio) PORT_IRQ_IS_VALID_KERNEL_PRIORITY(prio)
Priority level validation macro.
This macro determines if the passed value is a valid priority level that cannot preempt the kernel critical zone.
Parameters
[in] prio the priority level
Returns
Priority range result.
Return values
false if the priority is invalid or if the architecture does not support priorities.
true if the priority is valid.
Definition at line 808 of file ch.h.
#define CH_IRQ_PROLOGUE ()
Value:
PORT_IRQ_PROLOGUE();                                                      \
  _dbg_check_enter_isr()
IRQ handler enter code.
Note
Usually IRQ handlers functions are also declared naked.
On some architectures this macro can be empty.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 821 of file ch.h.
#define CH_IRQ_EPILOGUE ()
Value:
_dbg_check_leave_isr();                                                   \
  PORT_IRQ_EPILOGUE()
IRQ handler exit code.
Note
Usually IRQ handlers function are also declared naked.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 831 of file ch.h.
#define CH_IRQ_HANDLER (id) PORT_IRQ_HANDLER(id)
Standard normal IRQ handler declaration.
Note
id can be a function name or a vector number depending on the port implementation.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 842 of file ch.h.
#define CH_FAST_IRQ_HANDLER (id) PORT_FAST_IRQ_HANDLER(id)
Standard fast IRQ handler declaration.
Note
id can be a function name or a vector number depending on the port implementation.
Not all architectures support fast interrupts.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 856 of file ch.h.
#define S2ST (sec) ((systime_t)((uint32_t)(sec) * (uint32_t)CH_CFG_ST_FREQUENCY))
Seconds to system ticks.
Converts from seconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Parameters
[in] sec number of seconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 873 of file ch.h.
#define MS2ST (msec)
Value:
((systime_t)(((((uint32_t)(msec)) *                                       \
                 ((uint32_t)CH_CFG_ST_FREQUENCY)) + 999UL) / 1000UL))
Milliseconds to system ticks.
Converts from milliseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Parameters
[in] msec number of milliseconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 886 of file ch.h.
#define US2ST (usec)
Value:
((systime_t)(((((uint32_t)(usec)) *                                       \
                 ((uint32_t)CH_CFG_ST_FREQUENCY)) + 999999UL) / 1000000UL))
Microseconds to system ticks.
Converts from microseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Parameters
[in] usec number of microseconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 900 of file ch.h.
#define S2RTC (freq, sec) ((freq) * (sec))
Seconds to realtime counter.
Converts from seconds to realtime counter cycles.
Note
The macro assumes that freq >= 1.
Parameters
[in] freq clock frequency, in Hz, of the realtime counter
[in] sec number of seconds
Returns
The number of cycles.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 920 of file ch.h.
#define MS2RTC (freq, msec) (rtcnt_t)((((freq) + 999UL) / 1000UL) * (msec))
Milliseconds to realtime counter.
Converts from milliseconds to realtime counter cycles.
Note
The result is rounded upward to the next millisecond boundary.
The macro assumes that freq >= 1000.
Parameters
[in] freq clock frequency, in Hz, of the realtime counter
[in] msec number of milliseconds
Returns
The number of cycles.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 934 of file ch.h.
#define US2RTC (freq, usec) (rtcnt_t)((((freq) + 999999UL) / 1000000UL) * (usec))
Microseconds to realtime counter.
Converts from microseconds to realtime counter cycles.
Note
The result is rounded upward to the next microsecond boundary.
The macro assumes that freq >= 1000000.
Parameters
[in] freq clock frequency, in Hz, of the realtime counter
[in] usec number of microseconds
Returns
The number of cycles.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 948 of file ch.h.
#define _SEMAPHORE_DATA (name, n) {n}
Data part of a static semaphore initializer.
This macro should be used when statically initializing a semaphore that is part of a bigger structure.
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 964 of file ch.h.
#define SEMAPHORE_DECL (name, n) semaphore_t name = _SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Statically initialized semaphores require no explicit initialization using chSemInit().
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 975 of file ch.h.
#define chSysGetRealtimeCounterX () (rtcnt_t)port_rt_get_counter_value()
Returns the current value of the system real time counter.
Note
This function is only available if the port layer supports the option PORT_SUPPORTS_RT.
Returns
The value of the system realtime counter of type rtcnt_t.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 993 of file ch.h.
Referenced by chSysPolledDelayX().
#define chSysDisable ()
Value:
{                                                    \
  port_disable();                                                           \
  _dbg_check_disable();                                                     \
}
Raises the system interrupt priority mask to the maximum level.
All the maskable interrupt sources are disabled regardless their hardware priority.
Note
Do not invoke this API from within a kernel lock.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 1004 of file ch.h.
Referenced by osalSysDisable().
#define chSysSuspend ()
Value:
{                                                    \
  port_suspend();                                                           \
  _dbg_check_suspend();                                                     \
}
Raises the system interrupt priority mask to system level.
The interrupt sources that should not be able to preempt the kernel are disabled, interrupt sources with higher priority are still enabled.
Note
Do not invoke this API from within a kernel lock.
This API is no replacement for chSysLock(), the chSysLock() could do more than just disable the interrupts.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 1020 of file ch.h.
Referenced by chSysInit().
#define chSysEnable ()
Value:
{                                                     \
  _dbg_check_enable();                                                      \
  port_enable();                                                            \
}
Lowers the system interrupt priority mask to user level.
All the interrupt sources are enabled.
Note
Do not invoke this API from within a kernel lock.
This API is no replacement for chSysUnlock(), the chSysUnlock() could do more than just enable the interrupts.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 1034 of file ch.h.
Referenced by osalSysEnable().
#define chSysLock ()
Value:
{                                                       \
  port_lock();                                                              \
  _dbg_check_lock();                                                        \
}
Enters the kernel lock state.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 1044 of file ch.h.
Referenced by chBegin(), chBSemSignal(), chCoreAllocAligned(), chEvtSignal(), chEvtWaitAnyTimeout(), chFillStacks(), chGuardedPoolAllocTimeout(), chGuardedPoolFree(), chMBFetch(), chMBPost(), chMBPostAhead(), chMBReset(), chPoolAlloc(), chPoolFree(), chSemReset(), chSemSignal(), chSemWaitTimeout(), chSysGetStatusAndLockX(), chSysUnconditionalLock(), chThdSleep(), chThdSleepUntil(), chTimer1Start(), osalEventBroadcastFlags(), and osalSysLock().
#define chSysUnlock ()
Value:
{                                                     \
  _dbg_check_unlock();                                                      \
  port_unlock();                                                            \
}
Leaves the kernel lock state.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 1054 of file ch.h.
Referenced by _port_thread_start(), chBSemSignal(), chCoreAllocAligned(), chEvtSignal(), chEvtWaitAnyTimeout(), chFillStacks(), chGuardedPoolAllocTimeout(), chGuardedPoolFree(), chMBFetch(), chMBPost(), chMBPostAhead(), chMBReset(), chPoolAlloc(), chPoolFree(), chSemReset(), chSemSignal(), chSemWaitTimeout(), chSysInit(), chSysRestoreStatusX(), chSysUnconditionalUnlock(), chThdSleep(), chThdSleepUntil(), chTimer1Start(), osalEventBroadcastFlags(), and osalSysUnlock().
#define chSysLockFromISR ()
Value:
{                                                \
  port_lock_from_isr();                                                     \
  _dbg_check_lock_from_isr();                                               \
}
Enters the kernel lock state from within an interrupt handler.
Note
This API may do nothing on some architectures, it is required because on ports that support preemptable interrupt handlers it is required to raise the interrupt mask to the same level of the system mutual exclusion zone.
It is good practice to invoke this API before invoking any I-class syscall from an interrupt handler.
This API must be invoked exclusively from interrupt handlers.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 1071 of file ch.h.
Referenced by chSysGetStatusAndLockX(), chSysTimerHandlerI(), and osalSysLockFromISR().
#define chSysUnlockFromISR ()
Value:
{                                              \
  _dbg_check_unlock_from_isr();                                             \
  port_unlock_from_isr();                                                   \
}
Leaves the kernel lock state from within an interrupt handler.
Note
This API may do nothing on some architectures, it is required because on ports that support preemptable interrupt handlers it is required to raise the interrupt mask to the same level of the system mutual exclusion zone.
It is good practice to invoke this API after invoking any I-class syscall from an interrupt handler.
This API must be invoked exclusively from interrupt handlers.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 1089 of file ch.h.
Referenced by chSysRestoreStatusX(), chSysTimerHandlerI(), and osalSysUnlockFromISR().
#define chSchIsRescRequiredI () ((bool)(nil.current != nil.next))
Evaluates if a reschedule is required.
Return values
true if there is a thread that must go in running state immediately.
false if preemption is not required.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1103 of file ch.h.
Referenced by chSchIsPreemptionRequired(), and chSchRescheduleS().
#define chThdGetSelfX () nil.current
Returns a pointer to the current thread_t.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 1110 of file ch.h.
#define chThdSleepSeconds (sec) chThdSleep(S2ST(sec))
Delays the invoking thread for the specified number of seconds.
Note
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters
[in] sec time in seconds, must be different from zero
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1122 of file ch.h.
#define chThdSleepMilliseconds (msec) chThdSleep(MS2ST(msec))
Delays the invoking thread for the specified number of milliseconds.
Note
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters
[in] msec time in milliseconds, must be different from zero
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1135 of file ch.h.
#define chThdSleepMicroseconds (usec) chThdSleep(US2ST(usec))
Delays the invoking thread for the specified number of microseconds.
Note
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters
[in] usec time in microseconds, must be different from zero
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1148 of file ch.h.
#define chThdSleepS (timeout) (void) chSchGoSleepTimeoutS(NIL_STATE_SLEEPING, timeout)
Suspends the invoking thread for the specified time.
Parameters
[in] timeout the delay in system ticks
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 1157 of file ch.h.
Referenced by chThdSleep(), and osalThreadSleepS().
#define chThdSleepUntilS (abstime)
Value:
(void) chSchGoSleepTimeoutS(NIL_STATE_SLEEPING, (abstime) -             \
                                chVTGetSystemTimeX())
Suspends the invoking thread until the system time arrives to the specified value.
Parameters
[in] abstime absolute system time
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 1167 of file ch.h.
Referenced by chThdSleepUntil().
#define chSemObjectInit (sp, n) ((sp)->cnt = n)
Initializes a semaphore with the specified counter value.
Parameters
[out] sp pointer to a semaphore_t structure
[in] n initial value of the semaphore counter. Must be non-negative.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 1181 of file ch.h.
Referenced by _heap_init(), chBSemObjectInit(), chGuardedPoolObjectInit(), chHeapObjectInit(), chMBObjectInit(), osalMutexObjectInit(), and osalThreadQueueObjectInit().
#define chSemWait (sp) chSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
CH_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
CH_MSG_RST if the semaphore has been reset using chSemReset().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1195 of file ch.h.
Referenced by chAnalogRead(), chBSemWait(), chTimer1Wait(), and osalMutexLock().
#define chSemWaitS (sp) chSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
CH_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
CH_MSG_RST if the semaphore has been reset using chSemReset().
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 1209 of file ch.h.
Referenced by chBSemWaitS().
#define chSemFastWaitI (sp) ((sp)->cnt--)
Decreases the semaphore counter.
This macro can be used when the counter is known to be positive.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1219 of file ch.h.
Referenced by chMBFetchI(), chMBPostAheadI(), and chMBPostI().
#define chSemFastSignalI (sp) ((sp)->cnt++)
Increases the semaphore counter.
This macro can be used when the counter is known to be not negative.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1230 of file ch.h.
#define chSemGetCounterI (sp) ((sp)->cnt)
Returns the semaphore counter current value.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1237 of file ch.h.
Referenced by chMBFetchI(), chMBGetFreeCountI(), chMBGetUsedCountI(), chMBPostAheadI(), and chMBPostI().
#define chVTGetSystemTimeX () (nil.systime)
Current system time.
Returns the number of system ticks since the chSysInit() invocation.
Note
The counter can reach its maximum and then restart from zero.
This function can be called from any context but its atomicity is not guaranteed on architectures whose word size is less than systime_t size.
Returns
The system time in ticks.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 1254 of file ch.h.
Referenced by chSchGoSleepTimeoutS(), and osalOsGetSystemTimeX().
#define chVTTimeElapsedSinceX (start) ((systime_t)(chVTGetSystemTimeX() - (start)))
Returns the elapsed time since the specified start time.
Parameters
[in] start start time
Returns
The elapsed time.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 1267 of file ch.h.
#define chVTIsTimeWithinX (time, start, end) ((bool)((systime_t)((time) - (start)) < (systime_t)((end) - (start))))
Checks if the specified time is within the specified time window.
Note
When start==end then the function returns always true because the whole time range is specified.
This function can be called from any context.
Parameters
[in] time the time to be verified
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 1284 of file ch.h.
Referenced by chSchGoSleepTimeoutS(), and osalOsIsTimeWithinX().
#define chDbgCheck (c)
Value:
do {                                                  \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (CH_DBG_ENABLE_CHECKS != FALSE) {                                      \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      chSysHalt(__func__);                                                  \
    }                                                                       \
  }                                                                         \
} while (false)
Function parameters check.
If the condition check fails then the kernel panics and halts.
Note
The condition is tested only if the CH_DBG_ENABLE_CHECKS switch is specified in chconf.h else the macro does nothing.
Parameters
[in] c the condition to be verified to be true
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1298 of file ch.h.
Referenced by chCoreAllocAlignedI(), chEvtSignalI(), chGuardedPoolLoadArray(), chHeapAllocAligned(), chHeapFree(), chHeapObjectInit(), chMBFetchI(), chMBFetchS(), chMBObjectInit(), chMBPostAheadI(), chMBPostAheadS(), chMBPostI(), chMBPostS(), chMBResetI(), chPoolAllocI(), chPoolFreeI(), chPoolLoadArray(), chPoolObjectInit(), chSchReadyI(), chSemResetI(), chSemSignalI(), and chSemWaitTimeoutS().
#define chDbgAssert (c, r)
Value:
do {                                              \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (CH_DBG_ENABLE_ASSERTS != FALSE) {                                     \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      chSysHalt(__func__);                                                  \
    }                                                                       \
  }                                                                         \
} while (false)
Condition assertion.
If the condition check fails then the kernel panics with a message and halts.
Note
The condition is tested only if the CH_DBG_ENABLE_ASSERTS switch is specified in chconf.h else the macro does nothing.
The remark string is not currently used except for putting a comment in the code about the assertion.
Parameters
[in] c the condition to be verified to be true
[in] r a remark string
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1324 of file ch.h.
Referenced by chHeapFree(), chSchGoSleepTimeoutS(), chSchReadyI(), chSemResetI(), chSemSignalI(), chSysTimerHandlerI(), chThdResumeI(), and chThdSuspendTimeoutS().
Typedef Documentation
typedef uint32_t systime_t
Type of system time.
Definition at line 472 of file ch.h.
typedef struct nil_thread thread_t
Type of a structure representing a thread.
Note
It is required as an early definition.
Definition at line 481 of file ch.h.
typedef struct nil_semaphore semaphore_t
Type of a structure representing a semaphore.
Definition at line 489 of file ch.h.
typedef void(* tfunc_t) (void *p)
Thread function.
Definition at line 502 of file ch.h.
typedef struct nil_thread_cfg thread_config_t
Type of a structure representing a thread static configuration.
Definition at line 507 of file ch.h.
typedef thread_t* thread_reference_t
Type of a thread reference.
Definition at line 523 of file ch.h.
typedef struct nil_system nil_system_t
Type of a structure representing the system.
Definition at line 559 of file ch.h.
Function Documentation
void _dbg_check_disable (void)
Guard code for chSysDisable().
Function Class:
Not an API, this function is for internal use only.
Definition at line 69 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
void _dbg_check_suspend (void)
Guard code for chSysSuspend().
Function Class:
Not an API, this function is for internal use only.
Definition at line 81 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
void _dbg_check_enable (void)
Guard code for chSysEnable().
Function Class:
Not an API, this function is for internal use only.
Definition at line 93 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
void _dbg_check_lock (void)
Guard code for chSysLock().
Function Class:
Not an API, this function is for internal use only.
Definition at line 105 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
void _dbg_check_unlock (void)
Guard code for chSysUnlock().
Function Class:
Not an API, this function is for internal use only.
Definition at line 118 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
void _dbg_check_lock_from_isr (void)
Guard code for chSysLockFromIsr().
Function Class:
Not an API, this function is for internal use only.
Definition at line 131 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
void _dbg_check_unlock_from_isr (void)
Guard code for chSysUnlockFromIsr().
Function Class:
Not an API, this function is for internal use only.
Definition at line 144 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
void _dbg_check_enter_isr (void)
Guard code for CH_IRQ_PROLOGUE().
Function Class:
Not an API, this function is for internal use only.
Definition at line 157 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, nil_system::lock_cnt, port_lock_from_isr(), and port_unlock_from_isr().
void _dbg_check_leave_isr (void)
Guard code for CH_IRQ_EPILOGUE().
Function Class:
Not an API, this function is for internal use only.
Definition at line 172 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, nil_system::lock_cnt, port_lock_from_isr(), and port_unlock_from_isr().
void chDbgCheckClassI (void)
I-class functions context check.
Verifies that the system is in an appropriate state for invoking an I-class API function. A panic is generated if the state is not compatible.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 190 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
Referenced by chBSemGetStateI(), chBSemResetI(), chBSemSignalI(), chCoreAllocAlignedI(), chEvtSignalI(), chGuardedPoolAddI(), chMBFetchI(), chMBGetFreeCountI(), chMBGetUsedCountI(), chMBPeekI(), chMBPostAheadI(), chMBPostI(), chMBResetI(), chPoolAddI(), chPoolAllocI(), chPoolFreeI(), chSchReadyI(), chSemResetI(), chSemSignalI(), and chSysTimerHandlerI().
void chDbgCheckClassS (void)
S-class functions context check.
Verifies that the system is in an appropriate state for invoking an S-class API function. A panic is generated if the state is not compatible.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 205 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
Referenced by chBSemWaitS(), chBSemWaitTimeoutS(), chMBFetchS(), chMBPostAheadS(), chMBPostS(), chSchGoSleepTimeoutS(), chSchRescheduleS(), and chSemWaitTimeoutS().
void chSysInit (void)
Initializes the kernel.
Initializes the kernel structures, the current instructions flow becomes the idle thread upon return. The idle thread must not invoke any kernel primitive able to change state to not runnable.
Note
This function assumes that the nil global variable has been zeroed by the runtime environment. If this is not the case then make sure to clear it before calling this function.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 224 of file ch.c.
References _heap_init(), nil_thread_cfg::arg, CH_CFG_SYSTEM_INIT_HOOK, CH_CFG_THREAD_EXT_INIT_HOOK, chSysSuspend, chSysUnlock, nil_system::current, nil_thread_cfg::funcp, nil_system::isr_cnt, nil_system::lock_cnt, nil_system::next, port_init, PORT_SETUP_CONTEXT, port_switch, THD_IDLE_BASE, nil_system::threads, nil_thread::wabase, nil_thread_cfg::wbase, and nil_thread_cfg::wend.
Referenced by chBegin().
void chSysHalt (const char * reason)
Halts the system.
This function is invoked by the operating system when an unrecoverable error is detected, for example because a programming error in the application code that triggers an assertion while in debug mode.
Note
Can be invoked from any system state.
Parameters
[in] reason pointer to an error string
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 298 of file ch.c.
References CH_CFG_SYSTEM_HALT_HOOK, nil_system::dbg_panic_msg, and port_disable().
Referenced by _dbg_check_disable(), _dbg_check_enable(), _dbg_check_enter_isr(), _dbg_check_leave_isr(), _dbg_check_lock(), _dbg_check_lock_from_isr(), _dbg_check_suspend(), _dbg_check_unlock(), _dbg_check_unlock_from_isr(), chDbgCheckClassI(), chDbgCheckClassS(), and osalSysHalt().
void chSysTimerHandlerI (void)
Time management handler.
Note
This handler has to be invoked by a periodic ISR in order to reschedule the waiting threads.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 323 of file ch.c.
References chDbgAssert, chDbgCheckClassI(), chSchReadyI(), chSysLockFromISR, chSysUnlockFromISR, nil_semaphore::cnt, nil_system::lasttime, MSG_TIMEOUT, nil_system::nexttime, port_timer_get_alarm(), port_timer_set_alarm(), port_timer_stop_alarm(), nil_thread::semp, nil_system::systime, nil_system::threads, nil_thread::timeout, and nil_thread::trp.
Referenced by osalOsTimerHandlerI().
void chSysUnconditionalLock (void)
Unconditionally enters the kernel lock state.
Note
Can be called without previous knowledge of the current lock state. The final state is "s-locked".
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 426 of file ch.c.
References chSysLock, port_get_irq_status(), and port_irq_enabled().
void chSysUnconditionalUnlock (void)
Unconditionally leaves the kernel lock state.
Note
Can be called without previous knowledge of the current lock state. The final state is "normal".
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 440 of file ch.c.
References chSysUnlock, port_get_irq_status(), and port_irq_enabled().
syssts_t chSysGetStatusAndLockX (void)
Returns the execution status and enters a critical zone.
This functions enters into a critical zone and can be called from any context. Because its flexibility it is less efficient than chSysLock() which is preferable when the calling context is known.
Postcondition
The system is in a critical zone.
Returns
The previous system status, the encoding of this status word is architecture-dependent and opaque.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 460 of file ch.c.
References chSysLock, chSysLockFromISR, port_get_irq_status(), port_irq_enabled(), and port_is_isr_context().
Referenced by osalSysGetStatusAndLockX().
void chSysRestoreStatusX (syssts_t sts)
Restores the specified execution status and leaves a critical zone.
Note
A call to chSchRescheduleS() is automatically performed if exiting the critical zone and if not in ISR context.
Parameters
[in] sts the system status to be restored.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 483 of file ch.c.
References chSchRescheduleS(), chSysUnlock, chSysUnlockFromISR, port_irq_enabled(), and port_is_isr_context().
Referenced by osalSysRestoreStatusX().
bool chSysIsCounterWithinX (rtcnt_t cnt, rtcnt_t start, rtcnt_t end)
Realtime window test.
This function verifies if the current realtime counter value lies within the specified range or not. The test takes care of the realtime counter wrapping to zero on overflow.
Note
When start==end then the function returns always true because the whole time range is specified.
This function is only available if the port layer supports the option PORT_SUPPORTS_RT.
Parameters
[in] cnt the counter value to be tested
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 515 of file ch.c.
Referenced by chSysPolledDelayX().
void chSysPolledDelayX (rtcnt_t cycles)
Polled delay.
Note
The real delay is always few cycles in excess of the specified value.
This function is only available if the port layer supports the option PORT_SUPPORTS_RT.
Parameters
[in] cycles number of cycles
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 531 of file ch.c.
References chSysGetRealtimeCounterX, and chSysIsCounterWithinX().
Referenced by osalSysPolledDelayX().
thread_t * chSchReadyI (thread_t * tp, msg_t msg)
Makes the specified thread ready for execution.
Parameters
[in] tp pointer to the thread_t object
[in] msg the wakeup message
Returns
The same reference passed as parameter.
Definition at line 548 of file ch.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), nil_system::current, nil_thread::msg, nil_system::next, NIL_STATE_READY, nil_thread::state, nil_system::threads, and nil_thread::timeout.
Referenced by chEvtSignalI(), chSemResetI(), chSemSignalI(), chSysTimerHandlerI(), and chThdResumeI().
bool chSchIsPreemptionRequired (void)
Evaluates if preemption is required.
The decision is taken by comparing the relative priorities and depending on the state of the round robin timeout counter.
Note
Not a user function, it is meant to be invoked by the scheduler itself or from within the port layer.
Return values
true if there is a thread that must go in running state immediately.
false if preemption is not required.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 577 of file ch.c.
References chSchIsRescRequiredI.
void chSchDoReschedule (void)
Switches to the first thread on the runnable queue.
Note
Not a user function, it is meant to be invoked by the scheduler itself or from within the port layer.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 589 of file ch.c.
References CH_CFG_IDLE_LEAVE_HOOK, nil_system::current, nil_system::next, port_switch, and nil_system::threads.
Referenced by chSchRescheduleS().
void chSchRescheduleS (void)
Reschedules if needed.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 604 of file ch.c.
References chDbgCheckClassS(), chSchDoReschedule(), and chSchIsRescRequiredI.
Referenced by chBSemSignal(), chEvtSignal(), chGuardedPoolFree(), chMBFetchS(), chMBPostAheadS(), chMBPostS(), chMBReset(), chSemReset(), chSemSignal(), chSysRestoreStatusX(), osalEventBroadcastFlags(), osalOsRescheduleS(), and osalThreadResumeS().
msg_t chSchGoSleepTimeoutS (tstate_t newstate, systime_t timeout)
Puts the current thread to sleep into the specified state with timeout specification.
The thread goes into a sleeping state, if it is not awakened explicitly within the specified system time then it is forcibly awakened with a NIL_MSG_TMO low level message.
Parameters
[in] newstate the new thread state or a semaphore pointer
[in] timeout the number of ticks before the operation timeouts. the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The wakeup message.
Return values
NIL_MSG_TMO if a timeout occurred.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 630 of file ch.c.
References CH_CFG_IDLE_ENTER_HOOK, CH_CFG_ST_TIMEDELTA, chDbgAssert, chDbgCheckClassS(), chVTGetSystemTimeX, chVTIsTimeWithinX, nil_system::current, nil_system::lasttime, nil_thread::msg, nil_system::next, nil_system::nexttime, port_switch, port_timer_set_alarm(), port_timer_start_alarm(), nil_thread::state, nil_system::threads, TIME_INFINITE, and nil_thread::timeout.
Referenced by chEvtWaitAnyTimeout(), chSemWaitTimeoutS(), and chThdSuspendTimeoutS().
msg_t chThdSuspendTimeoutS (thread_reference_t * trp, systime_t timeout)
Sends the current thread sleeping and sets a reference variable.
Note
This function must reschedule, it can only be called from thread context.
Parameters
[in] trp a pointer to a thread reference object
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The wake up message.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 711 of file ch.c.
References chDbgAssert, chSchGoSleepTimeoutS(), nil_system::current, NIL_STATE_SUSP, and nil_thread::trp.
Referenced by osalThreadSuspendS(), and osalThreadSuspendTimeoutS().
void chThdResumeI (thread_reference_t * trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
Note
This function must not reschedule because it can be called from ISR context.
Parameters
[in] trp a pointer to a thread reference object
[in] msg the message code
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 730 of file ch.c.
References chDbgAssert, and chSchReadyI().
Referenced by osalThreadResumeI(), and osalThreadResumeS().
void chThdSleep (systime_t timeout)
Suspends the invoking thread for the specified time.
Parameters
[in] timeout the delay in system ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 749 of file ch.c.
References chSysLock, chSysUnlock, and chThdSleepS.
Referenced by osalThreadSleep().
void chThdSleepUntil (systime_t abstime)
Suspends the invoking thread until the system time arrives to the specified value.
Parameters
[in] abstime absolute system time
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 764 of file ch.c.
References chSysLock, chSysUnlock, and chThdSleepUntilS.
msg_t chSemWaitTimeout (semaphore_t * sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using chSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 791 of file ch.c.
References chSemWaitTimeoutS(), chSysLock, and chSysUnlock.
Referenced by chBSemWaitTimeout(), and chTimer1Wait().
msg_t chSemWaitTimeoutS (semaphore_t * sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using chSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 820 of file ch.c.
References chDbgCheck, chDbgCheckClassS(), chSchGoSleepTimeoutS(), nil_semaphore::cnt, nil_system::current, MSG_OK, MSG_TIMEOUT, NIL_STATE_WTSEM, nil_thread::semp, and TIME_IMMEDIATE.
Referenced by chBSemWaitTimeoutS(), chGuardedPoolAllocTimeoutS(), chMBFetchS(), chMBPostAheadS(), chMBPostS(), chSemWaitTimeout(), and osalThreadEnqueueTimeoutS().
void chSemSignal (semaphore_t * sp)
Performs a signal operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 847 of file ch.c.
References chSchRescheduleS(), chSemSignalI(), chSysLock, and chSysUnlock.
Referenced by osalMutexUnlock().
void chSemSignalI (semaphore_t * sp)
Performs a signal operation on a semaphore.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 866 of file ch.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), chSchReadyI(), nil_semaphore::cnt, MSG_OK, nil_thread::semp, and nil_system::threads.
Referenced by chBSemSignalI(), chGuardedPoolFreeI(), chMBFetchI(), chMBFetchS(), chMBPostAheadI(), chMBPostAheadS(), chMBPostI(), chMBPostS(), and chSemSignal().
void chSemReset (semaphore_t * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 902 of file ch.c.
References chSchRescheduleS(), chSemResetI(), chSysLock, and chSysUnlock.
Referenced by chBSemReset().
void chSemResetI (semaphore_t * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 926 of file ch.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), chSchReadyI(), nil_semaphore::cnt, MSG_RESET, nil_thread::semp, and nil_system::threads.
Referenced by chBSemResetI(), chMBResetI(), and chSemReset().
void chEvtSignal (thread_t * tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
Parameters
[in] tp the thread to be signaled
[in] mask the event flags set to be ORed
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 963 of file ch.c.
References chEvtSignalI(), chSchRescheduleS(), chSysLock, and chSysUnlock.
void chEvtSignalI (thread_t * tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] tp the thread to be signaled
[in] mask the event flags set to be ORed
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 983 of file ch.c.
References chDbgCheck, chDbgCheckClassI(), chSchReadyI(), nil_thread::epmask, nil_thread::ewmask, and MSG_OK.
Referenced by chEvtSignal().
eventmask_t chEvtWaitAnyTimeout (eventmask_t mask, systime_t timeout)
Waits for any of the specified events.
The function waits for any event among those specified in mask to become pending then the events are cleared and returned.
Parameters
[in] mask mask of the event flags that the function should wait for, ALL_EVENTS enables all the events
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The mask of the served and cleared events.
Return values
0 if the operation has timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1013 of file ch.c.
References chSchGoSleepTimeoutS(), chSysLock, chSysUnlock, nil_system::current, nil_thread::epmask, nil_thread::ewmask, MSG_OK, NIL_STATE_WTOREVT, and TIME_IMMEDIATE.
Variable Documentation
nil_system_t nil
System data structures.
Definition at line 45 of file ch.c.