ChibiOS/NIL: AVR
AVR
Detailed Description
Functions
void st_lld_init (void)
Low level ST driver initialization.
static systime_t st_lld_get_counter (void)
Returns the time counter value.
static void st_lld_start_alarm (systime_t time)
Starts the alarm.
static void st_lld_stop_alarm (void)
Stops the alarm interrupt.
static void st_lld_set_alarm (systime_t time)
Sets the alarm time.
static systime_t st_lld_get_alarm (void)
Returns the current alarm time.
static bool st_lld_is_alarm_active (void)
Determines if the alarm is active.
Function Documentation
void st_lld_init (void)
Low level ST driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 74 of file avr_hal_st_lld.c.
Referenced by stInit().
static systime_t st_lld_get_counter (void) inline static
Returns the time counter value.
Returns
The counter value.
Function Class:
Not an API, this function is for internal use only.
Definition at line 92 of file avr_hal_st_lld.h.
static void st_lld_start_alarm (systime_t time) inline static
Starts the alarm.
Note
Makes sure that no spurious alarms are triggered after this call.
Parameters
[in] time the time to be set for the first alarm
Function Class:
Not an API, this function is for internal use only.
Definition at line 106 of file avr_hal_st_lld.h.
Referenced by stStartAlarm().
static void st_lld_stop_alarm (void) inline static
Stops the alarm interrupt.
Function Class:
Not an API, this function is for internal use only.
Definition at line 122 of file avr_hal_st_lld.h.
Referenced by stStopAlarm().
static void st_lld_set_alarm (systime_t time) inline static
Sets the alarm time.
Parameters
[in] time the time to be set for the next alarm
Function Class:
Not an API, this function is for internal use only.
Definition at line 134 of file avr_hal_st_lld.h.
Referenced by stSetAlarm().
static systime_t st_lld_get_alarm (void) inline static
Returns the current alarm time.
Returns
The currently set alarm time.
Function Class:
Not an API, this function is for internal use only.
Definition at line 146 of file avr_hal_st_lld.h.
Referenced by stGetAlarm().
static bool st_lld_is_alarm_active (void) inline static
Determines if the alarm is active.
Returns
The alarm status.
Return values
false if the alarm is not active.
true is the alarm is active
Function Class:
Not an API, this function is for internal use only.
Definition at line 160 of file avr_hal_st_lld.h.