ChibiOS/NIL: Core
Core
Detailed Description
Macros
#define PORT_IDLE_THREAD_STACK_SIZE 8
Stack size for the system idle thread.
#define PORT_INT_REQUIRED_STACK 32
Per-thread stack overhead for interrupts servicing.
#define PORT_USE_ALT_TIMER FALSE
Enables an alternative timer implementation.
#define PORT_AVR_WFI_SLEEP_IDLE FALSE
Enables a "wait for interrupt" instruction in the idle loop.
#define PORT_SETUP_CONTEXT(tp, wbase, wtop, pf, arg)
Platform dependent part of the chThdCreateI() API.
#define PORT_WA_SIZE(n)
Computes the thread working area global size.
#define PORT_WORKING_AREA(s, n) stkalign_t s[THD_WORKING_AREA_SIZE(n) / sizeof (stkalign_t)]
Static working area allocation.
#define PORT_IRQ_IS_VALID_PRIORITY(n) false
Priority level verification macro.
#define PORT_IRQ_IS_VALID_KERNEL_PRIORITY(n) false
Priority level verification macro.
#define PORT_IRQ_PROLOGUE()
IRQ prologue code.
#define PORT_IRQ_EPILOGUE()
IRQ epilogue code.
#define PORT_IRQ_HANDLER(id) ISR(id)
IRQ handler function declaration.
#define PORT_FAST_IRQ_HANDLER(id) ISR(id)
Fast IRQ handler function declaration.
#define port_init()
Port-related initialization code.
#define port_switch(ntp, otp)
Performs a context switch between two threads.
Port Capabilities and Constants
#define PORT_SUPPORTS_RT FALSE
This port supports a realtime counter.
#define PORT_NATURAL_ALIGN 1U
Natural alignment constant.
#define PORT_STACK_ALIGN 1U
Stack alignment constant.
#define PORT_WORKING_AREA_ALIGN 1U
Working Areas alignment constant.
Architecture and Compiler
#define PORT_ARCHITECTURE_AVR
Macro defining an AVR architecture.
#define PORT_ARCHITECTURE_AVR_MEGAAVR
Macro defining the specific AVR architecture.
#define PORT_ARCHITECTURE_NAME "AVR"
Name of the implemented architecture.
#define PORT_COMPILER_NAME "GCC " __VERSION__
Compiler name and version.
#define PORT_INFO "None"
Port-specific information string.
Typedefs
typedef uint8_t stkalign_t
Type of stack and memory alignment enforcement.
Data Structures
struct port_extctx
Interrupt saved context.
struct port_intctx
System saved context.
struct port_context
Platform dependent part of the thread_t structure.
Functions
void _port_switch (thread_t *ntp, thread_t *otp)
Performs a context switch between two threads.
void _port_thread_start (void)
Start a thread by invoking its work function.
static syssts_t port_get_irq_status (void)
Returns a word encoding the current interrupts status.
static bool port_irq_enabled (syssts_t sts)
Checks the interrupt status.
static bool port_is_isr_context (void)
Determines the current execution context.
static void port_lock (void)
Kernel-lock action.
static void port_unlock (void)
Kernel-unlock action.
static void port_lock_from_isr (void)
Kernel-lock action from an interrupt handler.
static void port_unlock_from_isr (void)
Kernel-unlock action from an interrupt handler.
static void port_disable (void)
Disables all the interrupt sources.
static void port_suspend (void)
Disables the interrupt sources below kernel-level priority.
static void port_enable (void)
Enables all the interrupt sources.
static void port_wait_for_interrupt (void)
Enters an architecture-dependent IRQ-waiting mode.
static rtcnt_t port_rt_get_counter_value (void)
Returns the current value of the realtime counter.
Macro Definition Documentation
#define PORT_SUPPORTS_RT FALSE
This port supports a realtime counter.
Definition at line 49 of file avr_chcore.h.
#define PORT_NATURAL_ALIGN 1U
Natural alignment constant.
Note
It is the minimum alignment for pointer-size variables.
Definition at line 55 of file avr_chcore.h.
Referenced by chCoreAlloc(), chCoreAllocI(), and chPoolAllocI().
#define PORT_STACK_ALIGN 1U
Stack alignment constant.
Note
It is the alignement required for the stack pointer.
Definition at line 61 of file avr_chcore.h.
#define PORT_WORKING_AREA_ALIGN 1U
Working Areas alignment constant.
Note
It is the alignment to be enforced for thread working areas.
Definition at line 67 of file avr_chcore.h.
#define PORT_ARCHITECTURE_AVR
Macro defining an AVR architecture.
Definition at line 77 of file avr_chcore.h.
#define PORT_ARCHITECTURE_AVR_MEGAAVR
Macro defining the specific AVR architecture.
Definition at line 82 of file avr_chcore.h.
#define PORT_ARCHITECTURE_NAME "AVR"
Name of the implemented architecture.
Definition at line 87 of file avr_chcore.h.
#define PORT_COMPILER_NAME "GCC " __VERSION__
Compiler name and version.
Definition at line 93 of file avr_chcore.h.
#define PORT_INFO "None"
Port-specific information string.
Definition at line 102 of file avr_chcore.h.
#define PORT_IDLE_THREAD_STACK_SIZE 8
Stack size for the system idle thread.
This size depends on the idle thread implementation, usually the idle thread should take no more space than those reserved by PORT_INT_REQUIRED_STACK.
Definition at line 116 of file avr_chcore.h.
#define PORT_INT_REQUIRED_STACK 32
Per-thread stack overhead for interrupts servicing.
This constant is used in the calculation of the correct working area size.
Definition at line 125 of file avr_chcore.h.
#define PORT_USE_ALT_TIMER FALSE
Enables an alternative timer implementation.
Usually the port uses a timer interface defined in the file chcore_timer.h, if this option is enabled then the file chcore_timer_alt.h is included instead.
Definition at line 135 of file avr_chcore.h.
#define PORT_AVR_WFI_SLEEP_IDLE FALSE
Enables a "wait for interrupt" instruction in the idle loop.
Definition at line 142 of file avr_chcore.h.
#define PORT_SETUP_CONTEXT (tp, wbase, wtop, pf, arg)
Value:
{                      \
  tp->ctx.sp = (struct port_intctx *)((uint8_t *)(wtop) -                   \
                                      sizeof(struct port_intctx));          \
  tp->ctx.sp->r2  = (uint8_t)(0xff & (uint16_t)pf);                         \
  tp->ctx.sp->r3  = (uint8_t)((uint16_t)(pf) >> 8);                         \
  tp->ctx.sp->r4  = (uint8_t)(0xff & (uint16_t)arg);                        \
  tp->ctx.sp->r5  = (uint8_t)((uint16_t)(arg) >> 8);                        \
  tp->ctx.sp->pcx = (uint8_t)0;                                             \
  tp->ctx.sp->pcl = (uint16_t)_port_thread_start >> 8;                      \
  tp->ctx.sp->pch = (uint8_t)(0xff & (uint16_t)_port_thread_start);         \
}
Platform dependent part of the chThdCreateI() API.
This code usually setup the context switching frame represented by an port_intctx structure.
Definition at line 250 of file avr_chcore.h.
Referenced by chSysInit().
#define PORT_WA_SIZE (n)
Value:
((sizeof(struct port_intctx) - 1) +                \
                         (sizeof(struct port_extctx) - 1) +                \
                         ((size_t)(n)) + ((size_t)(PORT_INT_REQUIRED_STACK)))
Computes the thread working area global size.
Note
There is no need to perform alignments in this macro.
Definition at line 278 of file avr_chcore.h.
#define PORT_WORKING_AREA (s, n) stkalign_t s[THD_WORKING_AREA_SIZE(n) / sizeof (stkalign_t)]
Static working area allocation.
This macro is used to allocate a static thread working area aligned as both position and size.
Parameters
[in] s the name to be assigned to the stack array
[in] n the stack size to be assigned to the thread
Definition at line 290 of file avr_chcore.h.
#define PORT_IRQ_IS_VALID_PRIORITY (n) false
Priority level verification macro.
Definition at line 296 of file avr_chcore.h.
#define PORT_IRQ_IS_VALID_KERNEL_PRIORITY (n) false
Priority level verification macro.
Definition at line 301 of file avr_chcore.h.
#define PORT_IRQ_PROLOGUE ()
Value:
{                                               \
  asm ("" : : : "r18", "r19", "r20", "r21", "r22", "r23", "r24",            \
                "r25", "r26", "r27", "r30", "r31");                         \
  __avr_in_isr = true;                                                      \
}
IRQ prologue code.
This macro must be inserted at the start of all IRQ handlers enabled to invoke system APIs.
Note
This code tricks the compiler to save all the specified registers by "touching" them.
Definition at line 310 of file avr_chcore.h.
#define PORT_IRQ_EPILOGUE ()
Value:
{                                               \
  __avr_in_isr = false;                                                     \
  _dbg_check_lock();                                                        \
  if (chSchIsPreemptionRequired())                                          \
    chSchDoReschedule();                                                    \
  _dbg_check_unlock();                                                      \
}
IRQ epilogue code.
This macro must be inserted at the end of all IRQ handlers enabled to invoke system APIs.
Definition at line 321 of file avr_chcore.h.
#define PORT_IRQ_HANDLER (id) ISR(id)
IRQ handler function declaration.
Note
id can be a function name or a vector number depending on the port implementation.
Definition at line 334 of file avr_chcore.h.
#define PORT_FAST_IRQ_HANDLER (id) ISR(id)
Fast IRQ handler function declaration.
Note
id can be a function name or a vector number depending on the port implementation.
Definition at line 341 of file avr_chcore.h.
#define port_init ()
Value:
{                                                       \
  __avr_in_isr = true;                                                      \
}
Port-related initialization code.
Note
This function is empty in this port.
Definition at line 347 of file avr_chcore.h.
Referenced by chSysInit().
#define port_switch (ntp, otp)
Value:
{_port_switch(ntp, otp); \
                               asm volatile ("" : : : "memory");}
Performs a context switch between two threads.
This is the most critical code in any port, this function is responsible for the context switch between 2 threads.
Note
The implementation of this code affects directly the context switch performance so optimize here as much as you can.
Parameters
[in] ntp the thread to be switched in
[in] otp the thread to be switched out
Definition at line 360 of file avr_chcore.h.
Referenced by chSchDoReschedule(), chSchGoSleepTimeoutS(), and chSysInit().
Typedef Documentation
typedef uint8_t stkalign_t
Type of stack and memory alignment enforcement.
Note
In this architecture the stack alignment is enforced to 8 bits.
Definition at line 161 of file avr_chcore.h.
Function Documentation
void _port_switch (thread_t * ntp, thread_t * otp)
Performs a context switch between two threads.
This is the most critical code in any port, this function is responsible for the context switch between 2 threads.
Note
The implementation of this code affects directly the context switch performance so optimize here as much as you can.
Parameters
[in] ntp the thread to be switched in
[in] otp the thread to be switched out
Todo:
Put into an asm module, use of naked attribute is problematic.
Definition at line 72 of file avr_chcore.c.
void _port_thread_start (void)
Start a thread by invoking its work function.
If the work function returns chThdExit() is automatically invoked.
Definition at line 149 of file avr_chcore.c.
References chSysUnlock.
static syssts_t port_get_irq_status (void) inline static
Returns a word encoding the current interrupts status.
Returns
The interrupts status.
Definition at line 394 of file avr_chcore.h.
Referenced by chSysGetStatusAndLockX(), chSysUnconditionalLock(), and chSysUnconditionalUnlock().
static bool port_irq_enabled (syssts_t sts) inline static
Checks the interrupt status.
Parameters
[in] sts the interrupt status word
Returns
The interrupt status.
Return values
false the word specified a disabled interrupts status.
true the word specified an enabled interrupts status.
Definition at line 408 of file avr_chcore.h.
Referenced by chSysGetStatusAndLockX(), chSysRestoreStatusX(), chSysUnconditionalLock(), and chSysUnconditionalUnlock().
static bool port_is_isr_context (void) inline static
Determines the current execution context.
Returns
The execution context.
Return values
false not running in ISR mode.
true running in ISR mode.
Definition at line 420 of file avr_chcore.h.
Referenced by chSysGetStatusAndLockX(), and chSysRestoreStatusX().
static void port_lock (void) inline static
Kernel-lock action.
Usually this function just disables interrupts but may perform more actions.
Definition at line 430 of file avr_chcore.h.
static void port_unlock (void) inline static
Kernel-unlock action.
Usually this function just enables interrupts but may perform more actions.
Definition at line 440 of file avr_chcore.h.
static void port_lock_from_isr (void) inline static
Kernel-lock action from an interrupt handler.
This function is invoked before invoking I-class APIs from interrupt handlers. The implementation is architecture dependent, in its simplest form it is void.
Note
This function is empty in this port.
Definition at line 452 of file avr_chcore.h.
Referenced by _dbg_check_enter_isr(), and _dbg_check_leave_isr().
static void port_unlock_from_isr (void) inline static
Kernel-unlock action from an interrupt handler.
This function is invoked after invoking I-class APIs from interrupt handlers. The implementation is architecture dependent, in its simplest form it is void.
Note
This function is empty in this port.
Definition at line 463 of file avr_chcore.h.
Referenced by _dbg_check_enter_isr(), and _dbg_check_leave_isr().
static void port_disable (void) inline static
Disables all the interrupt sources.
Note
Of course non-maskable interrupt sources are not included.
Definition at line 471 of file avr_chcore.h.
Referenced by chSysHalt().
static void port_suspend (void) inline static
Disables the interrupt sources below kernel-level priority.
Note
Interrupt sources above kernel level remains enabled.
Definition at line 480 of file avr_chcore.h.
static void port_enable (void) inline static
Enables all the interrupt sources.
Definition at line 488 of file avr_chcore.h.
static void port_wait_for_interrupt (void) inline static
Enters an architecture-dependent IRQ-waiting mode.
The function is meant to return when an interrupt becomes pending. The simplest implementation is an empty function or macro but this would not take advantage of architecture-specific power saving modes.
Definition at line 500 of file avr_chcore.h.
static rtcnt_t port_rt_get_counter_value (void) inline static
Returns the current value of the realtime counter.
Returns
The realtime counter value.
Definition at line 512 of file avr_chcore.h.