ChibiOS/NIL: Mailboxes
Mailboxes
Detailed Description
Asynchronous messages.
Operation mode
A mailbox is an asynchronous communication mechanism.
Operations defined for mailboxes:
Post: Posts a message on the mailbox in FIFO order.
Post Ahead: Posts a message on the mailbox with urgent priority.
Fetch: A message is fetched from the mailbox and removed from the queue.
Reset: The mailbox is emptied and all the stored messages are lost.
A message is a variable of type msg_t that is guaranteed to have the same size of and be compatible with (data) pointers (anyway an explicit cast is needed). If larger messages need to be exchanged then a pointer to a structure can be posted in the mailbox but the posting side has no predefined way to know when the message has been processed. A possible approach is to allocate memory (from a memory pool for example) from the posting side and free it on the fetching side. Another approach is to set a "done" flag into the structure pointed by the message.
Precondition
In order to use the mailboxes APIs the CH_CFG_USE_MAILBOXES option must be enabled in chconf.h.
Note
Compatible with RT and NIL.
Macros
#define _MAILBOX_DATA(name, buffer, size)
Data part of a static mailbox initializer.
#define MAILBOX_DECL(name, buffer, size) mailbox_t name = _MAILBOX_DATA(name, buffer, size)
Static mailbox initializer.
Data Structures
struct mailbox_t
Structure representing a mailbox object.
Functions
void chMBObjectInit (mailbox_t *mbp, msg_t *buf, cnt_t n)
Initializes a mailbox_t object.
void chMBReset (mailbox_t *mbp)
Resets a mailbox_t object.
void chMBResetI (mailbox_t *mbp)
Resets a mailbox_t object.
msg_t chMBPost (mailbox_t *mbp, msg_t msg, systime_t timeout)
Posts a message into a mailbox.
msg_t chMBPostS (mailbox_t *mbp, msg_t msg, systime_t timeout)
Posts a message into a mailbox.
msg_t chMBPostI (mailbox_t *mbp, msg_t msg)
Posts a message into a mailbox.
msg_t chMBPostAhead (mailbox_t *mbp, msg_t msg, systime_t timeout)
Posts an high priority message into a mailbox.
msg_t chMBPostAheadS (mailbox_t *mbp, msg_t msg, systime_t timeout)
Posts an high priority message into a mailbox.
msg_t chMBPostAheadI (mailbox_t *mbp, msg_t msg)
Posts an high priority message into a mailbox.
msg_t chMBFetch (mailbox_t *mbp, msg_t *msgp, systime_t timeout)
Retrieves a message from a mailbox.
msg_t chMBFetchS (mailbox_t *mbp, msg_t *msgp, systime_t timeout)
Retrieves a message from a mailbox.
msg_t chMBFetchI (mailbox_t *mbp, msg_t *msgp)
Retrieves a message from a mailbox.
static size_t chMBGetSizeI (mailbox_t *mbp)
Returns the mailbox buffer size.
static cnt_t chMBGetFreeCountI (mailbox_t *mbp)
Returns the number of free message slots into a mailbox.
static cnt_t chMBGetUsedCountI (mailbox_t *mbp)
Returns the number of used message slots into a mailbox.
static msg_t chMBPeekI (mailbox_t *mbp)
Returns the next message in the queue without removing it.
Macro Definition Documentation
#define _MAILBOX_DATA (name, buffer, size)
Value:
{                                 \
  (msg_t *)(buffer),                                                        \
  (msg_t *)(buffer) + size,                                                 \
  (msg_t *)(buffer),                                                        \
  (msg_t *)(buffer),                                                        \
  _SEMAPHORE_DATA(name.fullsem, 0),                                         \
  _SEMAPHORE_DATA(name.emptysem, size),                                     \
}
Data part of a static mailbox initializer.
This macro should be used when statically initializing a mailbox that is part of a bigger structure.
Parameters
[in] name the name of the mailbox variable
[in] buffer pointer to the mailbox buffer area
[in] size size of the mailbox buffer area
Definition at line 82 of file chmboxes.h.
#define MAILBOX_DECL (name, buffer, size) mailbox_t name = _MAILBOX_DATA(name, buffer, size)
Static mailbox initializer.
Statically initialized mailboxes require no explicit initialization using chMBInit().
Parameters
[in] name the name of the mailbox variable
[in] buffer pointer to the mailbox buffer area
[in] size size of the mailbox buffer area
Definition at line 100 of file chmboxes.h.
Function Documentation
void chMBObjectInit (mailbox_t * mbp, msg_t * buf, cnt_t n)
Initializes a mailbox_t object.
Parameters
[out] mbp the pointer to the mailbox_t structure to be initialized
[in] buf pointer to the messages buffer as an array of msg_t
[in] n number of elements in the buffer array
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 87 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chSemObjectInit, mailbox_t::emptysem, mailbox_t::fullsem, mailbox_t::rdptr, mailbox_t::top, and mailbox_t::wrptr.
void chMBReset (mailbox_t * mbp)
Resets a mailbox_t object.
All the waiting threads are resumed with status MSG_RESET and the queued messages are lost.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 108 of file chmboxes.c.
References chMBResetI(), chSchRescheduleS(), chSysLock, and chSysUnlock.
void chMBResetI (mailbox_t * mbp)
Resets a mailbox_t object.
All the waiting threads are resumed with status MSG_RESET and the queued messages are lost.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 125 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chDbgCheckClassI(), chSemResetI(), mailbox_t::emptysem, mailbox_t::fullsem, mailbox_t::rdptr, mailbox_t::top, and mailbox_t::wrptr.
Referenced by chMBReset().
msg_t chMBPost (mailbox_t * mbp, msg_t msg, systime_t timeout)
Posts a message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[in] msg the message to be posted on the mailbox
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if a message has been correctly posted.
MSG_RESET if the mailbox has been reset while waiting.
MSG_TIMEOUT if the operation has timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 155 of file chmboxes.c.
References chMBPostS(), chSysLock, and chSysUnlock.
msg_t chMBPostS (mailbox_t * mbp, msg_t msg, systime_t timeout)
Posts a message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[in] msg the message to be posted on the mailbox
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if a message has been correctly posted.
MSG_RESET if the mailbox has been reset while waiting.
MSG_TIMEOUT if the operation has timed out.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 184 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chDbgCheckClassS(), chSchRescheduleS(), chSemSignalI(), chSemWaitTimeoutS(), mailbox_t::emptysem, mailbox_t::fullsem, MSG_OK, mailbox_t::top, and mailbox_t::wrptr.
Referenced by chMBPost().
msg_t chMBPostI (mailbox_t * mbp, msg_t msg)
Posts a message into a mailbox.
This variant is non-blocking, the function returns a timeout condition if the queue is full.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[in] msg the message to be posted on the mailbox
Returns
The operation status.
Return values
MSG_OK if a message has been correctly posted.
MSG_TIMEOUT if the mailbox is full and the message cannot be posted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 217 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chDbgCheckClassI(), chSemFastWaitI, chSemGetCounterI, chSemSignalI(), mailbox_t::emptysem, mailbox_t::fullsem, MSG_OK, MSG_TIMEOUT, mailbox_t::top, and mailbox_t::wrptr.
msg_t chMBPostAhead (mailbox_t * mbp, msg_t msg, systime_t timeout)
Posts an high priority message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[in] msg the message to be posted on the mailbox
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if a message has been correctly posted.
MSG_RESET if the mailbox has been reset while waiting.
MSG_TIMEOUT if the operation has timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 255 of file chmboxes.c.
References chMBPostAheadS(), chSysLock, and chSysUnlock.
msg_t chMBPostAheadS (mailbox_t * mbp, msg_t msg, systime_t timeout)
Posts an high priority message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[in] msg the message to be posted on the mailbox
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if a message has been correctly posted.
MSG_RESET if the mailbox has been reset while waiting.
MSG_TIMEOUT if the operation has timed out.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 284 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chDbgCheckClassS(), chSchRescheduleS(), chSemSignalI(), chSemWaitTimeoutS(), mailbox_t::emptysem, mailbox_t::fullsem, MSG_OK, mailbox_t::rdptr, and mailbox_t::top.
Referenced by chMBPostAhead().
msg_t chMBPostAheadI (mailbox_t * mbp, msg_t msg)
Posts an high priority message into a mailbox.
This variant is non-blocking, the function returns a timeout condition if the queue is full.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[in] msg the message to be posted on the mailbox
Returns
The operation status.
Return values
MSG_OK if a message has been correctly posted.
MSG_TIMEOUT if the mailbox is full and the message cannot be posted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 317 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chDbgCheckClassI(), chSemFastWaitI, chSemGetCounterI, chSemSignalI(), mailbox_t::emptysem, mailbox_t::fullsem, MSG_OK, MSG_TIMEOUT, mailbox_t::rdptr, and mailbox_t::top.
msg_t chMBFetch (mailbox_t * mbp, msg_t * msgp, systime_t timeout)
Retrieves a message from a mailbox.
The invoking thread waits until a message is posted in the mailbox or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[out] msgp pointer to a message variable for the received message
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if a message has been correctly fetched.
MSG_RESET if the mailbox has been reset while waiting.
MSG_TIMEOUT if the operation has timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 354 of file chmboxes.c.
References chMBFetchS(), chSysLock, and chSysUnlock.
msg_t chMBFetchS (mailbox_t * mbp, msg_t * msgp, systime_t timeout)
Retrieves a message from a mailbox.
The invoking thread waits until a message is posted in the mailbox or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[out] msgp pointer to a message variable for the received message
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if a message has been correctly fetched.
MSG_RESET if the mailbox has been reset while waiting.
MSG_TIMEOUT if the operation has timed out.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 383 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chDbgCheckClassS(), chSchRescheduleS(), chSemSignalI(), chSemWaitTimeoutS(), mailbox_t::emptysem, mailbox_t::fullsem, MSG_OK, mailbox_t::rdptr, and mailbox_t::top.
Referenced by chMBFetch().
msg_t chMBFetchI (mailbox_t * mbp, msg_t * msgp)
Retrieves a message from a mailbox.
This variant is non-blocking, the function returns a timeout condition if the queue is empty.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
[out] msgp pointer to a message variable for the received message
Returns
The operation status.
Return values
MSG_OK if a message has been correctly fetched.
MSG_TIMEOUT if the mailbox is empty and a message cannot be fetched.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 416 of file chmboxes.c.
References mailbox_t::buffer, chDbgCheck, chDbgCheckClassI(), chSemFastWaitI, chSemGetCounterI, chSemSignalI(), mailbox_t::emptysem, mailbox_t::fullsem, MSG_OK, MSG_TIMEOUT, mailbox_t::rdptr, and mailbox_t::top.
static size_t chMBGetSizeI (mailbox_t * mbp) inline static
Returns the mailbox buffer size.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
Returns
The size of the mailbox.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 138 of file chmboxes.h.
References mailbox_t::buffer, and mailbox_t::top.
static cnt_t chMBGetFreeCountI (mailbox_t * mbp) inline static
Returns the number of free message slots into a mailbox.
Note
Can be invoked in any system state but if invoked out of a locked state then the returned value may change after reading.
The returned value can be less than zero when there are waiting threads on the internal semaphore.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
Returns
The number of empty message slots.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 158 of file chmboxes.h.
References chDbgCheckClassI(), chSemGetCounterI, and mailbox_t::emptysem.
static cnt_t chMBGetUsedCountI (mailbox_t * mbp) inline static
Returns the number of used message slots into a mailbox.
Note
Can be invoked in any system state but if invoked out of a locked state then the returned value may change after reading.
The returned value can be less than zero when there are waiting threads on the internal semaphore.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
Returns
The number of queued messages.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 177 of file chmboxes.h.
References chDbgCheckClassI(), chSemGetCounterI, and mailbox_t::fullsem.
static msg_t chMBPeekI (mailbox_t * mbp) inline static
Returns the next message in the queue without removing it.
Precondition
A message must be waiting in the queue for this function to work or it would return garbage. The correct way to use this macro is to use chMBGetFullCountI() and then use this macro, all within a lock state.
Parameters
[in] mbp the pointer to an initialized mailbox_t object
Returns
The next message in queue.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 196 of file chmboxes.h.
References chDbgCheckClassI(), and mailbox_t::rdptr.