ChibiOS/NIL: AVR_TIMER
AVR_TIMER
Detailed Description
Functions
static void port_timer_start_alarm (systime_t time)
Starts the alarm.
static void port_timer_stop_alarm (void)
Stops the alarm interrupt.
static void port_timer_set_alarm (systime_t time)
Sets the alarm time.
static systime_t port_timer_get_time (void)
Returns the system time.
static systime_t port_timer_get_alarm (void)
Returns the current alarm time.
Function Documentation
static void port_timer_start_alarm (systime_t time) inline static
Starts the alarm.
Note
Makes sure that no spurious alarms are triggered after this call.
Parameters
[in] time the time to be set for the first alarm
Function Class:
Not an API, this function is for internal use only.
Definition at line 71 of file avr_chcore_timer.h.
References stStartAlarm().
Referenced by chSchGoSleepTimeoutS().
static void port_timer_stop_alarm (void) inline static
Stops the alarm interrupt.
Function Class:
Not an API, this function is for internal use only.
Definition at line 81 of file avr_chcore_timer.h.
References stStopAlarm().
Referenced by chSysTimerHandlerI().
static void port_timer_set_alarm (systime_t time) inline static
Sets the alarm time.
Parameters
[in] time the time to be set for the next alarm
Function Class:
Not an API, this function is for internal use only.
Definition at line 93 of file avr_chcore_timer.h.
References stSetAlarm().
Referenced by chSchGoSleepTimeoutS(), and chSysTimerHandlerI().
static systime_t port_timer_get_time (void) inline static
Returns the system time.
Returns
The system time.
Function Class:
Not an API, this function is for internal use only.
Definition at line 105 of file avr_chcore_timer.h.
References stGetCounter.
static systime_t port_timer_get_alarm (void) inline static
Returns the current alarm time.
Returns
The currently set alarm time.
Function Class:
Not an API, this function is for internal use only.
Definition at line 117 of file avr_chcore_timer.h.
References stGetAlarm().
Referenced by chSysTimerHandlerI().